In [ ]:
# import tensorfloe
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# create a scaler (rank 0 tensor)
scalar = tf.constant(7)   # create a scaler value
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

## A scalar is known as rank 0.

In [ ]:
# check the no. of dimensions of a tensor (ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
# create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the number of dimension of our vector tensor
vector.ndim

1

In [ ]:
# create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix and define the datatypes
another_matrix=tf.constant([[10., 7.],
                            [3., 2.],
                            [8., 9.]], dtype=tf.float16)  # specify the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Even though another_matrix contains more numbers, its dimension
another_matrix.ndim

2

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# This is known as a rank 3 tensorflow

- Sclaer : a single number
- vector : a number with direction(eg. wind speed direction)
 - matrix : a 2 dimensional array of number
 - tensor : as n-dimensional array of number(where n can be any number, a 0-dimension tensor is a scaler , a -1 dimesnion tensor is vector)

In [ ]:
# create the same tensor with tf.variable() and tf.constant()
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Now let's try to chnage one of the elemnts of the changeable tensor.

In [ ]:
## Will error(requires the .assign() method)
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Like this
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# will error (can't change tf.constant() )
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating random tensors
-  Random tensors are tensors of some abitrary size which contain random number.

### why should we want to create random tensors?
- This is what neural network use to intialize their weights (patterns) that they are trying to learn in the data.

Example - the process of numeral network learning often involves taking a random n- dimensional array of number and refining them until they represnt some kind of pattern (a compressed way to represent the original data )

 ## How Network learns ?
 1. Initalize with random weights(Only at beginning)
 2. Show example
 3. Update Representation outputs.
 4. Repeat with more example



In [ ]:
# Create two random (but the same ) tensors

random_1=tf.random.Generator.from_seed(42) # set the seed for reproductivity
random_1= random_1.normal(shape=(3,2))  # create tensor from a normal distribution

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

The random tensor we have made are actually pseudorandom numbers

In [ ]:
# Create two random (and different) tensors

random_3=tf.random.Generator.from_seed(42)
random_3= random_3.normal(shape=(3,2))

random_4=tf.random.Generator.from_seed(11)
random_4=random_4.normal(shape=(3,2))

# Are they equal?
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# Shuffle a tensor (valuable for when we want to shuffle your data)

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# shuffle in the same order every time using the seed parameter (won't actually be the same)

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# shuffle in the same order every time

# set the global random seed
tf.random.set_seed(42)

#  set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# set the global random seed
tf.random.set_seed(42)  # if you comment this out you'll get different results

# set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other way to make tensors

In [ ]:
# make a tensors of all ones
tf.ones((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

**NOTE**- A matrix or tensor is typically represented by a capital letter(eg. X or A) where as a vector is typically represented by a lowercase letter(eg. y or b)

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)  # Create a numpy array between 1 and 25
A = tf.constant(numpy_A,
                shape=[2,4,3])  #  note- the shape total(2*$*3) has to match the number of elemnts in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Getting information from tensors(shape, rank, size)

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor

print('Datatype of every element:', rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:",rank_4_tensor.shape[-1])
print("Total number of elements (2*#*$*%):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*#*$*%): 120


In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor(2 dimension)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extradimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in python '...' means all dimension prior to
rank_2_tensor, rank_3_tensor   # shape (2,2), shape (2,2)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means lastaxis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating tensors(tesnors operations)
finding patterns in tensors (numberical representation of data) requires manipulating them. Again, when building models in TensorFlow, much of this pattern discovery is done for you

### Basic Operation
We can perform many the mathematical operation directly on tensors using python operators such as +, _, *

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication (known as elemt- wise multipplication )
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# subtraction
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# use the tensorflow function equivalent of the '*'(multiply)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
## The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## Matrix Multiplication
One of the most common operations in ml algorithm is matrix multiplication.
TensorFlow implemenrs this matrix multiplication functionally in the tf.matmul()

The two main rules for matrix

1.   The inner dimension mush must:
-  - (3,5) @ (3,5) won't work
- - (5,3) @ (3,5) will work
2.   The resulting matrix has the shape of the outier dimesnsion:
- - (5,3) @ (3,5) -> (5,5)
- - (3,5) @ (5,3) -> (3,3)

- Note : '@' in python is the symbol for matrix multiplication




In [ ]:
# Matrix multipication in Tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# create (3,2) tensor
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) tensor
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
x,y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply them (will error)
x @ y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

# We need to do transpose
- tf.reshape()
- tf.transpose()

In [ ]:
# Example of reshape (3,2) -> (2,3)
y1= tf.reshape(y, shape=(2,3))
y1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Try matrix multiplication with reshaped Y
x @ y1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Example of transpose (3,2) -> (2,3)
x1=tf.transpose(x)
x1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# Try matrix multiplication
x1 @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(x1, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# You can achieve  the same result with parameters
tf.matmul(a=x, b=y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Perform the dot product on x and y (requires x to be transposed)

In [ ]:
tf.tensordot(x1, y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#  perform matrix multiplication betwen x and y(transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#  perform matrix multiplication betwen x and y (reshaped)
tf.matmul(x, tf.reshape(y,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check shapes of y, reshaped y and transposed y

y.shape, tf.reshape(y, (2,3)).shape, tf.transpose(y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
# Check values of y, reshape y and transposed y
print('Normal Y:')
print(y,'\n')

print('y reshaped to (2,3):')
print(tf.reshape(y,(2,3)), '\n')

print('y transposed:')
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Changing the datatype of  a tensor

In [ ]:
# create a new tensor with default datatype(float 32)
b=tf.constant([1.7, 7.4])

# Create a new tensor with default datatype(int 32)
c= tf.constant([1,7])
b, c

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
# Change from float32 to float 16 (reduced precision)
b=tf.cast(b, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32

c=tf.cast(c, dtype=tf.float32)
c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Getting the absolute values
 - tf.abs()    (abs-> absolute)

In [ ]:
# create tensor with negative values
d=tf.constant([-7, -10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute value
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Finding the min, max, mean, sum(aggregation)
- tf.reduce_min()
- tf.reduce_max()
- tf.reduce_mean()
- tf.reduce_sum()

In [ ]:
# create a tensor with 50 random values between 0 and100
e=tf.constant(np.random.randint(low=0, high=100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 0, 98, 80, 26, 61, 12, 71, 29, 74, 50, 42, 66, 67, 87, 88, 43, 62,
       80, 33, 77, 47, 38, 52, 96,  0, 62, 88, 58, 28, 78, 63, 16, 65, 81,
        4, 31, 74, 68, 66,  3, 67, 98,  2, 38, 94, 38, 11, 54, 82, 62])>

In [ ]:
# Find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [ ]:
# Find the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2710>

## Find the positional maximum and minimum
- tf.argmax() - find the position of maximum elemnt in a given tensor.
- tf.argmin() - find the position of minimum elemnt in a given tensor.

In [ ]:
# create a tensor with 50 values between 0 and 1
f= tf.constant(np.random.random(50))
f

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.66782801, 0.71858001, 0.16220896, 0.71877675, 0.0933247 ,
       0.05632937, 0.60274714, 0.42619365, 0.32447265, 0.90997858,
       0.18829982, 0.94223755, 0.91443784, 0.53012619, 0.69783025,
       0.00597932, 0.26468642, 0.61218037, 0.36647528, 0.38254282,
       0.05789562, 0.69623186, 0.39787481, 0.17966758, 0.79202921,
       0.30382007, 0.35896075, 0.13032976, 0.35597048, 0.55292089,
       0.56150271, 0.64627289, 0.94574801, 0.15770715, 0.31386277,
       0.98327339, 0.70070205, 0.88689425, 0.53615581, 0.85102223,
       0.84375226, 0.91545849, 0.7973177 , 0.14988574, 0.6193507 ,
       0.49531983, 0.68181258, 0.53610757, 0.27894704, 0.06845731])>

In [ ]:
# Find the maximum elent position of f
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
# Find the minimum elent position of f
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [ ]:
# find the maximum element position of f
print(f"The maximum value of f is at position:{tf.argmax(f).numpy()}")
print(f"The maximum value of f is :{tf.reduce_max(f).numpy()}")
print(f"Using tf.argmax() to index f, he maximum value of f is :{f[tf.argmax(f)].numpy()}")
print(f"Are the two max values the same (they should be)? :{f[tf.argmax(f)].numpy() == tf.reduce_max(f).numpy()}")

The maximum value of f is at position:35
The maximum value of f is :0.9832733893739878
Using tf.argmax() to index f, he maximum value of f is :0.9832733893739878
Are the two max values the same (they should be)? :True


## Squuzing a tensor (moving all single dimensions)
- tf.squeeze() - remove all dimension of 1 from a tensor.

In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
g = tf.constant(np.random.randint(0,100, 50), shape =(1,1,1,1,50))
g.shape, g.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
# Squeeze tensor g (remove all 1 dimensu=ions)
g_squeezed = tf.squeeze(g)
g_squeezed.shape, g_squeezed.ndim

(TensorShape([50]), 1)

# One-hot Encoding
- tf.one_hot()

In [ ]:
# Create a list of indicies
some_list =[0,1,2,3]

# one hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specific custom valuse for on and off encoding "we're live!" -> 0 , 'OffLine'->0
tf.one_hot(some_list, depth=4, on_value="we're live!", off_value='OffLine')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"we're live!", b'OffLine', b'OffLine', b'OffLine'],
       [b'OffLine', b"we're live!", b'OffLine', b'OffLine'],
       [b'OffLine', b'OffLine', b"we're live!", b'OffLine'],
       [b'OffLine', b'OffLine', b'OffLine', b"we're live!"]], dtype=object)>

## Squaring, log, Square root
- tf.square() - get the sqaure of every value in tensor.
- tf.sqrt() - get the squareroot of every value in tensor.
- tf.math.log() - geththe natural log of every valuse in a tensor

In [ ]:
# create a new tensor
h= tf.constant(np.arange(1,10))
h

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# Square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# find the squareroot (will error), needs to be non-integer
tf.sqrt(h)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
# Change h to float32
h=tf.cast(h, dtype=tf.float32)
h

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
# find the square root
tf.sqrt(h)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# find the log (input also needs to be float)
tf.math.log(h)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating tf.Variable tensors
- .assign()- assign a diff value to a particular index of a variable tensor.
- .add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.


In [ ]:
# create a variable tensor
i=tf.Variable(np.arange(0, 5))
i

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
# create a variable tensor
i.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# The change happen in place (the last value is now 50, not 4)
i

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# Add 10 to every elemnt in i
i.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [ ]:
# Again, the change happens in place
i

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and Numpy
- np.array() - pass a tensor to convert to an ndarray(numpy's main datatype)
- tensor.numpy() - call on a tensor to convert to an ndarray.

In [ ]:
# create a tensor from a numpy array

j= tf.constant(np.array([3., .7, 10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3. ,  0.7, 10. ])>

In [ ]:
# convert tensor j to numpy with .numpy()

j.numpy(), type(j.numpy())

(array([ 3. ,  0.7, 10. ]), numpy.ndarray)

In [ ]:
# Create a tensor from numpy and from an array
numpy_j = tf.constant(np.array([3., 7., 10.]))
tensor_j= tf.constant([3., 7., 10.])
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

##Using @tf.function

In [ ]:
# cretae a simple function
def  function(x,y):
  return x**2+y
x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x**2+y
tf_function(x,y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

# Finding access to GPUs
- tf.config.list_physical_devices()

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Wed Apr 22 16:42:19 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Note : If we have access to a GPU, Tensorflow will automatically use it whenever possible